name: run main.py

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: python main.py
      
      - name: commit files
        env:
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          set -eux
          README_CHANGES=$(git diff -- README.md | wc -l | xargs)
          git config --local user.email "githubbot@ian.mn"
          git config --local user.name "Ian Mckay [bot]"
          git add .
          git commit -m "Update data" -a || exit 0
          remote_repo="https://iann0036-bot:${BOT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:main
          if [[ "$README_CHANGES" == "0" ]]; then exit 0; fi
          INPUT_TAG="release-$(date +%Y%m%d%H%M%S)"
          awk '/^## / {section++} section == 1' README.md > /tmp/notes.md
          head -c 120000 /tmp/notes.md > /tmp/notes-truncated.md
          gh release create $INPUT_TAG -t "${INPUT_TAG}" -F /tmp/notes-truncated.md
